# Generated by Django 2.0.2 on 2018-02-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180222_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
